### ISSUE TITLE
MaxBot Content Censoring

### ISSUE THREAD

**Issue by thatmaxplayle** [maxplayle04/MaxBot#37]
I am working on content censoring, as well as an AutoMod system, for MaxBot. You will be able to disable this system, using the `mmbot/config` command, however, none of this functionality is available yet.

If you would like to join the **Beta Testing Team** for MaxBot, please **[get in touch](https://sites.google.com/view/maxplayle04/contact)**!

Everybody is more than welcome to expand on this idea, so please feel free to use the comments below to add your thoughts.

### Task overview:

- [x] Add censorable content dictionary, and index this on startup.
- [x] Add automatic moderation for all users messages (except administrators - where ignoreAdminMessages is enabled)
- [x] Add content filtering for when users add Community Compliments.
